### ISSUE TITLE
Specify which README.md to look in

### ISSUE THREAD

**Issue by sqs** [luttig/sg-sublime#4]
When it says my GOPATH is not defined, it should tell me which README.md to look in. Right now it just says "see README.md." This is referring to the sg-sublime README.md, but it might not be obvious to someone else.

**Comment by luttig** [comment]
We are redefining the way the GOPATH / godef error messages are displayed (will be displayed in browser), so closing this. This is a good point, so I'll make sure @wholien includes a direct link in the error message to make it unambiguous
