### ISSUE TITLE
Get GOPATH/GOROOT from GoSublime

### ISSUE THREAD

**Issue by sqs** [luttig/sg-sublime#5]
Can you just read these from `/home/sqs/.config/sublime-text-3/Packages/User/GoSublime.sublime-settings` or whatever? I had to set my GOPATH in that file and in the Sourcegraph.sublime-settings file.

**Comment by luttig** [comment]
Good idea. Done in https://github.com/luttig/sg-sublime/commit/6d189f3b411a89c4d7b5140319b45870d29e3847
