### ISSUE TITLE
Right-click action

### ISSUE THREAD

**Issue by sqs** [luttig/sg-sublime#6]
Can you make it so you can right-click on a Go identifier to open up the Sourcegraph Live window? Would make it easier to discover (instead of having to type the keybinding).

**Comment by luttig** [comment]
@sqs Do you mean a right-click menu option to **re**-open the window? I can do that pretty easily.

It should automatically open the browser when the user clicks on a Go identifier, though (always opens the first time, and reopens should also happen automatically pending CheckListeners support server-side)

**Comment by sqs** [comment]
Oh never mind. I see it is working automatically now! Can close this.
