### ISSUE TITLE
Opening browser fails on Linux

### ISSUE THREAD

**Issue by sqs** [luttig/sg-sublime#7]
In `open_live_channel` it calls `open <URL>` on Linux, but Linux `open` does not work like OS X `open`. You can use `xdg-open` on Linux instead of `open`, so the command ends up being `xdg-open <URL>`. There might be a better way (checking `$BROWSER` env var) but this should work for now.

**Comment by luttig** [comment]
Thanks for catching – this should be fixed in https://github.com/luttig/sg-sublime/commit/03cdc6afe1595cc0e1be712f6d5a01c53cc04420. Will look into reading from $BROWSER.
