### ISSUE TITLE
godef call needs -f filename flag

### ISSUE THREAD

**Issue by sqs** [luttig/sg-sublime#8]
Without the `-f filename` flag being passed to my godef (Go 1.6.2, Linux), godef's first line would just be a line number, like:

```
:56:2
type Foo { ...
```

This broke the plugin because it didn't see 2 colons and therefore thought it was a local def.

Passing the `-f` flag to godef fixed it. I found this necessary for the emacs plugin, too.

```diff
diff --git a/sg_sublime.py b/sg_sublime.py
index 1582a26..efbe04a 100644
--- a/sg_sublime.py
+++ b/sg_sublime.py
@@ -157,7 +157,7 @@ class SgDocCommand(sublime_plugin.EventListener):
                return str(len(buffer_before))
 
        def run_godef(self, view):
-               godef_args = ['godef', '-i', '-o', self.cursor_offset(), '-t']
+               godef_args = ['godef', '-i', '-o', self.cursor_offset(), '-t', '-f', view.file_name()]
                logging.info('[godef] Running shell command: %s' % ' '.join(godef_args))
 
                godef_output = None
```

**Comment by luttig** [comment]
Fixed in https://github.com/luttig/sg-sublime/commit/2fd014c0b07ed1d51ec90fa31c047f25c5123ec8
