### ISSUE TITLE
Does not handle consts

### ISSUE THREAD

**Issue by sqs** [luttig/sg-sublime#9]
The godef output for a const is not parsed properly, which means if you put the cursor over a const such as `http.StatusMovedPermanently` (an instance of which you can find in gorilla/mux mux.go), then the browser tries to go to https://staging.sourcegraph.com/github.com/golang/go@github.com/golang/go/-/def/GoPackage/net/http/-/const/-/info. This is probably because it's passing `?...&def=const` instead of parsing out the "const" from the godef output to get the name (which comes next). I had to handle this case specially in Emacs as well (and I see that the Emacs go-mode itself does the same).

**Comment by luttig** [comment]
fixed in https://github.com/luttig/sg-sublime/pull/10
